version: "3"
services:
  db:
    container_name: contactchain-db
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 30s
    volumes:
      - pgdata:/var/libpostgresql/data

  migration:
    container_name: contactchain-migration
    build:
      context: .
    command: npx prisma migrate dev
    depends_on:
      db:
        condition: service_healthy

  app:
    container_name: contactchain-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "npx prisma generate && npm run dev"
    stdin_open: true
    tty: true
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
volumes:
  pgdata:
